### PR TITLE
feat: FAQs

### PR DESCRIPTION
**Pull request by joebailey26**
# TIB Landing PR

## Changes

A brief list of changes

- 3 sections of FAQs with images

## Test Cases

What should the reviewer do and expect to happen when testing

1. Check spelling and all

### CODE REVIEW

**Review by joebailey26 — COMMENTED** [review]
**Let's add 'Are you a Trainer?':**
  - [x]  How to archive a client
  - [x]  How to unarchive a client
  - [x]  How to send a client an invite to TIB
  - [x]  How to edit client information
  - [x]  How to schedule a booking
  - [x]  How to view previous bookings
  - [x]  How to cancel a booking
  - [x]  How to use the calculators
  - [x]  How to create a new plan
  - [x]  How to edit plan notes
  - [x]  How to add a session
  - [x]  How to progress sessions
  - [x]  How to duplicate sessions
  - [x]  How to shift sessions
  - [x]  How to move sessions
  - [x]  How to print sessions
  - [x]  How to complete a session
  - [x] How to delete a session
  - [x]  Assigning colours to microcycles
  - [x]  How to use the WYSIWYG
  - [x]  How to cancel your subscription
  - [x]  How to upgrade or downgrade your subscription
  - [x]  How to change your password from the account page
  - [x]  How to change your password from the login page
  - [ ]  How to change from light mode to dark mode
  - [ ]  How to use your referral code
  - [ ]  How to embed TIB into your calendar
  - [ ]  How to opt-out of non-essential cookies

**Let's add 'Are you a Client?':**
  - [ ]  How to view your PTs profile
  - [ ]  How to change your password from the account page
  - [ ]  How to change your password from the login page
  - [ ]  How to edit your information
  - [ ]  How to request a booking
  - [ ]  How to cancel a booking request
  - [ ]  How to view your plans
  - [ ]  How to complete a session
  - [ ]  How to opt-out of non-essential cookies
  - [ ]  How to embed TIB into your calendar
  - [ ]  How to change from light mode to dark mode

**Comment by MikeyJL** [comment]
WIP will request review when ready

**Comment by MikeyJL** [comment]
@joebailey26 can review

**Comment by joebailey26** [comment]
This is brilliant, happy to put live now and do another PR for the GIFs/Videos/Images, or can hold off merging this until you get time to get that done

**Comment by MikeyJL** [comment]
Yea was gonna do GIFs but will take too long. Let's do another PR. Can you make a ticket and assign me pls @joebailey26

**Pull request merged**
